import dotenv from "dotenv";
dotenv.config();
import express from "express";
import { userrouter } from "./userrouter";
import cors from "cors";
import { contentrouter } from "./contentrouter";
import { brainrouter } from "./brainrouter";
import { tagrouter } from "./tagrouter";
import { dbconnection } from "./db";
import helmet from "helmet";
const app = express();
app.use(express.json());
app.use(cors());
app.use(helmet());
const PORT = Number(process.env.PORT) || 3000;
const DB_STRING = process.env.MONGODB_CONNECT as string;
dbconnection(DB_STRING);
app.use("/api/v1", userrouter);
app.use("/api/v1/content", contentrouter);
app.use("/api/v1/brain", brainrouter);
app.use("/api/v1/tagname", tagrouter);
app.listen(PORT, "0.0.0.0", () => {
  console.log("server running on:", PORT);
});
